#!/bin/sh
set -e
TARGET="dist"
echo "Preparing build directory"
mkdir -p build/ $TARGET
rm -rf build/* $TARGET/*
echo "Generating codepoints"
python3 ./scripts/make-codepoints.py
echo "Build CSS"
STYLE=""
if [ -z "$DEBUG" ]; then
    STYLE="--style=compressed"
fi
sass $STYLE scss/main.scss $TARGET/gufo-font.min.css
sass scss/main.scss $TARGET/gufo-font.css
echo "Copy Font"
cp webfonts/GufoFont-Regular.woff2 $TARGET/
echo "Post Processing"
python ./scripts/post-process.py