#!/bin/sh
# ---------------------------------------------------------------------
# Gufo Font: Build font distribution
# ---------------------------------------------------------------------
# Copyright (C) 2025, Gufo Labs
# ---------------------------------------------------------------------

set -e

TARGET=test # default
# Parse options
while [ $# -gt 0 ]; do
    case "$1" in
        --target=*)
            TARGET="${1#*=}"
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
    shift
done
# Preparations
DIST="dist/gufo-font"
echo "Post-processing target '$TARGET'"
echo "Preparing build directory"
mkdir -p build/ $DIST
rm -rf build/* $DIST/*
# Copy Font File
echo "Copy Font"
cp webfonts/GufoFont-Regular.woff2 $DIST/
# Clearing config
echo -n > build/_config.scss
# Generate codepoints
echo "Generating codepoints"
python3 ./scripts/make-codepoints.py
# Build css
echo "Build CSS"
MAIN_SCSS=scss/main.scss
HASH_PLACEHOLDER="XXXXXXXX"
case "$TARGET" in
    test)
        sass --no-source-map $MAIN_SCSS $DIST/gufo-font.css
        ;;
    docs)
        python ./scripts/configure-scss.py --font-hash-placeholder=${HASH_PLACEHOLDER}
        sass --style=compressed $MAIN_SCSS $DIST/gufo-font.css
        python ./scripts/post-process.py --hash-placeholder=${HASH_PLACEHOLDER}
        ;;
    package)
        cp README.md $DIST
        python3 ./scripts/make-package.py
        sass --no-source-map scss/main.scss $DIST/gufo-font.css
        sass --style=compressed $MAIN_SCSS $DIST/gufo-font.min.css
        ;;
    cdn)
        python ./scripts/configure-scss.py --font-hash-placeholder=${HASH_PLACEHOLDER}
        sass --style=compressed $MAIN_SCSS $DIST/gufo-font.css
        python ./scripts/post-process.py --hash-placeholder=${HASH_PLACEHOLDER}
        ;;
    *)
        echo "Unknown target: $TARGET"
        exit 1
        ;;
esac
